name: Lilaobot main workflow

on:
  push:
    branches: [ master ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploys Lilaobot GCP infrastructure with Terraform
    env:
      TF_VAR_gcp_credentials: ${{ secrets.GCP_SA_KEY }}
      TF_VAR_gcp_project: ${{ secrets.GCP_PROJECT }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2


      # Setup gcloud CLI
      - uses: google-github-actions/setup-gcloud@master
        with:
          version: '290.0.1'
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          project_id: ${{ secrets.GCP_PROJECT }}
          export_default_credentials: true

      - name: terraform apply
        uses: dflook/terraform-apply@v1
        with:
          path: terraform
          auto_approve: true
